version: 2.1
orbs:
  sfdx: circleci/salesforce-sfdx@2.2.0
jobs:
  install_authenticate:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
      - sfdx/auth:
          defaultusername: kiburedo@gmail.com
      - run:
          name: Run your SFDX commands here
          command: |
            sfdx force:org:display
workflows:
  basic-test:
    jobs:
      - install_authenticate